### ISSUE TITLE
Recomendaciones de mejora

### ISSUE THREAD

**Issue by gaposx** [marimeli/lim-2018-05-bc-core-pm-cipher#1]
**README**
* Buen trabajo en tu ReadMe incluyendo imágenes del proceso.
* Es bueno que hayas definido un público objetivo para tu aplicación pero no explicas el motivo de tu enfoque a usuarios de 17 a 30 años.
* Ten cuidado con el manejo del [markdown de GitHub](https://guides.github.com/features/mastering-markdown/), hay elementos que no se encuentran bien aplicados (por ejemplo listas).

**UX**
* Ten cuidado con el contraste de los inputs y su `placeholder`.

**HTML**
* Para seguir buenas prácticas, te sugerimos definir los `id` y `clases` de elementos en minúsculas y separados por guiones (-).
* Te sugerimos usar más etiquetas semánticas como `<header>`, `<section>`.

**JS**
* Tu aplicación no descifra cuando se usa números grandes (Ej: 1042) como offset. Te sugerimos que al momento de desarrollar alguna función trates de probar con varios números y hasta con valores o argumentos “extremos”. Recuerda que tu usuario puede "probar" con cualquier número.
* Para proyectos futuros, te sugerimos seguir la [guía de estilos de Laboratoria sobre JS](https://github.com/Laboratoria/js-style-guide).
* Recuerda que uno de los requerimientos del proyecto era estar implementado completamente en ES6, para ello, también deberías usar el `for..of`.

**CSS**
* Para que tu aplicación se vea mejor en pantallas pequeñas, también podrías usar [media queries](https://css-tricks.com/logic-in-media-queries/).

**TESTS**
* Siempre puedes desarrollar tests extra que te ayuden a probar con varios números y hasta con valores o argumentos “extremos”. Recuerda que tu usuario puede probar con cualquier número.

Buen trabajo!

**Comment by lissavcasas** [comment]
¡Gracias por el feedback, Gonzalo! Voy a trabajar en las correciones.
